version: 0.0
os: linux
files:
    - source: /
      destination: /home/pirate-mobile
hooks:
    ApplicationStop:
        - location: scripts/application_stop.sh
          timeout: 300
          runas: pirate-mobile
    BeforeInstall:
        - location: scripts/before_install.sh
          timeout: 300
          runas: pirate-mobile
    ApplicationStart:
        - location: scripts/application_start.sh
          timeout: 300
          runas: pirate-mobile
