export const EVENT_ORDER = {
    CREATE: 'EVENT_ORDER_CREATE',
    UPDATE: 'EVENT_ORDER_UPDATE',
    PROCESS: 'EVENT_ORDER_PROCESS',
    GENERATE: 'EVENT_ORDER_GENERATE',
    COMPLETE: 'EVENT_ORDER_COMPLETE',
};
