export const EVENT_ORDER = {
    CREATE: 'EVENT_ORDER_CREATE',
    UPDATE: 'EVENT_ORDER_UPDATE',
    PROCESS: 'EVENT_ORDER_PROCESS',
    GENERATE: 'EVENT_ORDER_GENERATE',
    COMPLETE: 'EVENT_ORDER_COMPLETE',
};

export const QUEUE_ORDER = {
    NAME: 'QUEUE_ORDER.NAME',
    RETRY_SEND_EMAIL_AFTER_ORDER: 'QUEUE_ORDER.RETRY_SEND_EMAIL_AFTER_ORDER',
};
