export const EVENT_ADMIN_USER = {
    CREATE: 'EVENT.ADMIN_USER.CREATE',
    UPDATE: 'EVENT.ADMIN_USER.UPDATE',
    RESET_PASSWORD: 'EVENT.ADMIN_USER.RESET_PASSWORD',
    LOGIN: 'EVENT.ADMIN_USER.LOGIN',
    QUERY: 'EVENT.ADMIN_USER.QUERY',
};
