export const EVENT_CUSTOMER = {
  CREATE: 'EVENT_CUSTOMER_CREATE',

  UPDATE_AVATAR: 'EVENT.CUSTOMER_UPDATE.INFORMATION.AVATAR',
  UPDATE_INFORMATION_PERSONAL: 'EVENT.CUSTOMER_UPDATE.INFORMATION.PERSONAL',
  UPDATE_INFORMATION_PRIVACY: 'EVENT.CUSTOMER_UPDATE.INFORMATION.PRIVACY',
  UPDATE_INFORMATION_CONTACT: 'EVENT.CUSTOMER_UPDATE.INFORMATION.CONTACT',
  UPDATE_FAMILY_EMERGENCY: 'EVENT.CUSTOMER_UPDATE.INFORMATION.FAMILY_EMERGENCY',
  UPDATE_MEDICAL_PROFILE: 'EVENT.CUSTOMER_UPDATE.MEDICAL_PROFILE',

  UPDATE_BASE_INFORMATION: 'EVENT.CUSTOMER_UPDATE.BASE_INFORMATION',

  CREATE_ADDRESS: 'EVENT.CUSTOMER_UPDATE.CREATE_ADDRESS',
  UPDATE_ADDRESS: 'EVENT.CUSTOMER_UPDATE.UPDATE_ADDRESS',
  REMOVE_ADDRESS: 'EVENT.CUSTOMER_UPDATE.REMOVE_ADDRESS',

  CREATE_BILLING: 'EVENT.CUSTOMER_UPDATE.CREATE_BILLING',
  UPDATE_BILLING: 'EVENT.CUSTOMER_UPDATE.UPDATE_BILLING',
  REMOVE_BILLING: 'EVENT.CUSTOMER_UPDATE.REMOVE_BILLING',

  UPDATE_TAG: 'EVENT.CUSTOMER_UPDATE.TAG',
  UPDATE_SURVEY: 'EVENT.CUSTOMER_UPDATE.SURVEY',
};
